- hosts: all
  roles:
    - base
    - python
    - akjones.remote-desktop-role
    - docker
    - aws
    - { role: ocha.dotnet-core, dotnet_ubuntu_package: "dotnet-dev-1.1.4" }
    - pablocrivella.nvm
