- name: install desktop packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  become: yes
  with_items:
    - ubuntu-desktop
    - xrdp
    - xfce4
    - xfce4-goodies 

- name: home xsession file
  copy:
    src: xsession
    dest: /home/ubuntu/.xsession
    owner: ubuntu
    group: ubuntu

- name: global xsession file
  copy:
    src: xsession
    dest: /etc/skel/.xsession

- name: restart xrdp service
  service:
    name: xrdp
    enabled: yes
    state: restarted

- name: upload xrdp.ini
  copy:
    src: xrdp.ini
    dest: /etc/xrdp/xrdp.ini

- name: upload xrdp.ini
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config

- name: restart ssh service
  service:
    name: ssh
    enabled: yes
    state: restarted

- name: setup password for default user
  user:
    name: ubuntu
    password: "{{ ubuntu_password }}"
    update_password: always
