- stat:
    path: ~/.nvm/nvm.sh
  register: nvm

- name: copy nvm install script
  copy:
    src: install_nvm.sh
    dest: /tmp/install_nvm.sh
    mode: 0755
  when: nvm.stat.exists == False

- name: run nvm installer
  command: /tmp/install_nvm.sh
  when: nvm.stat.exists == False

   
